Repository SLIIT-PROJECT-THIRD/Movie_Reservation, pull requests merged in 2022-05, with the labels that each got.

#1 feat(Login, Registration): Developed the Login screen and Registration screen
  Frontend/movie-reservation/package-lock.json
  Frontend/movie-reservation/package.json
  Frontend/movie-reservation/src/App.js
  Frontend/movie-reservation/src/asset/css/Home.css
  Frontend/movie-reservation/src/asset/css/Login.css
  Frontend/movie-reservation/src/asset/css/Navigation.css
  Frontend/movie-reservation/src/asset/css/Registration.css
  Frontend/movie-reservation/src/asset/image/Register.jpg
  Frontend/movie-reservation/src/asset/image/login.jpg
  Frontend/movie-reservation/src/components/Footer.js
  Frontend/movie-reservation/src/components/Header.js
  Frontend/movie-reservation/src/components/Home.js
  Frontend/movie-reservation/src/components/Login.js
  Frontend/movie-reservation/src/components/Registration.js
Labels: feat

#6 movie backend services implemented - reopened for status check
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/controller/MovieController.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/Movie.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/repository/MovieRepository.java
Labels: feat

#9 movie frontend and backend connected and implemented
  Backend/ds_assignment/pom.xml
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/controller/MovieController.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/controller/TheaterController.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/Movie.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/Theater.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/repository/TheaterRepository.java
  Frontend/movie-reservation/package-lock.json
  Frontend/movie-reservation/package.json
  Frontend/movie-reservation/public/index.html
  Frontend/movie-reservation/src/App.css
  Frontend/movie-reservation/src/App.js
  Frontend/movie-reservation/src/App.test.js
  Frontend/movie-reservation/src/components/dashboard/DashboardLoder.js
  Frontend/movie-reservation/src/components/dashboard/Navbar.js
  Frontend/movie-reservation/src/components/dashboard/Sidebar.js
  Frontend/movie-reservation/src/index.js
  Frontend/movie-reservation/src/pages/Movies/AddMovie.js
  Frontend/movie-reservation/src/pages/Movies/DisplayAll.js
  Frontend/movie-reservation/src/pages/Movies/Movie.css
  Frontend/movie-reservation/src/pages/Movies/UpdateMovie.js
  Frontend/movie-reservation/src/pages/Movies/firebase.js
  Frontend/movie-reservation/src/pages/Movies/imageUpload.js
  Frontend/movie-reservation/src/reportWebVitals.js
  Frontend/movie-reservation/src/setupTests.js
Labels: feat

#12 email is unique in the system. updated bacnend and frontend
  Backend/ds_assignment/pom.xml
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/controller/ManagerUserController.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/Login.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/ManagerUser.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/repository/ManagerUserRepository.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/service/Impl/ManagerServiceImpl.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/service/ManagerService.java
  Frontend/movie-reservation/src/App.js
  Frontend/movie-reservation/src/Services/PrivateRouteManager.js
  Frontend/movie-reservation/src/Services/SessionManager.js
  Frontend/movie-reservation/src/components/Header.js
  Frontend/movie-reservation/src/components/Login.js
  Frontend/movie-reservation/src/components/dashboard/Sidebar.js
  Frontend/movie-reservation/src/pages/Manager/AddManager.js
  Frontend/movie-reservation/src/pages/Manager/DisplayAll.js
  Frontend/movie-reservation/src/pages/Manager/Login.js
  Frontend/movie-reservation/src/pages/Manager/UpdateManager.js
  Frontend/movie-reservation/src/pages/Movies/AddMovie.js
Labels: feat

#25 User management v2
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/controller/UserController.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/User.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/repository/UserRepository.java
  Frontend/movie-reservation/.idea/inspectionProfiles/Project_Default.xml
  Frontend/movie-reservation/.idea/modules.xml
  Frontend/movie-reservation/.idea/movie-reservation.iml
  Frontend/movie-reservation/.idea/vcs.xml
  Frontend/movie-reservation/package-lock.json
  Frontend/movie-reservation/src/App.js
  Frontend/movie-reservation/src/Services/SessionManager.js
  Frontend/movie-reservation/src/components/Header.js
  Frontend/movie-reservation/src/components/Login.js
  Frontend/movie-reservation/src/components/Registration.js
  Frontend/movie-reservation/src/pages/Manager/Login.js
Labels: feat

#29 fix(Securityconfig): fixed registration issue
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/security/SecurityConfig.java
Labels: fix

#31 added hall price and removed unnecessary files
  .idea/Movie_Reservation.iml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  .idea/workspace.xml
  Backend/.idea/.gitignore
  Backend/.idea/Backend.iml
  Backend/.idea/artifacts/Backend_war_exploded.xml
  Backend/.idea/compiler.xml
  Backend/.idea/jarRepositories.xml
  Backend/.idea/libraries/Spring_5_2_3_RELEASE.xml
  Backend/.idea/libraries/Spring_Data_JPA_2_2_4_RELEASE.xml
  Backend/.idea/libraries/Spring_MVC_5_2_3_RELEASE.xml
  Backend/.idea/misc.xml
  Backend/.idea/modules.xml
  Backend/.idea/runConfigurations.xml
  Backend/.idea/vcs.xml
  Backend/.idea/workspace.xml
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/controller/TheaterController.java
  Backend/ds_assignment/src/main/java/com/movie_reservation/ds_assignment/model/Theater.java
  Frontend/.idea/.gitignore
  Frontend/movie-reservation/.idea/.gitignore
  Frontend/movie-reservation/.idea/inspectionProfiles/Project_Default.xml
  Frontend/movie-reservation/.idea/misc.xml
  Frontend/movie-reservation/.idea/modules.xml
  Frontend/movie-reservation/.idea/movie-reservation.iml
  Frontend/movie-reservation/.idea/vcs.xml
  Frontend/movie-reservation/package-lock.json
  Frontend/movie-reservation/src/pages/Theater/AddTheater.js
  Frontend/movie-reservation/src/pages/Theater/DisplayAll.js
  Frontend/movie-reservation/src/pages/Theater/UpdateTheater.js
  Frontend/package-lock.json
  pom.xml
Labels: enhancement, fix

#32 updated
  Frontend/movie-reservation/src/pages/Movies/DisplayAll.js
Labels: bug, fix
